### ISSUE TITLE
Fix images in "AngularJS code editor using UI-Bootstrap and CodeMirror"

### ISSUE THREAD

**Issue by DinisCruz-Dev** [DinisCruz/Book_Practical_AngularJS#16]
Here is the file with the image problems https://github.com/DinisCruz/Book_Practical_AngularJS/blob/master/manuscript/C1_Using_AngularJS-angularjscodeeditorusinguibootstrapandcodemirrordonewithoutusingjquery.md

Here is the correct images: http://blog.diniscruz.com/2013/06/angularjs-code-editor-using-ui.html

**Comment by DinisCruz** [comment]
done with latest refactoring
